### ISSUE TITLE
minor suggestions for the "Usage Notes"

### ISSUE THREAD

**Issue by ajgoyal** [bjmorgan/py-sc-fermi#23]
Suggestions:

1. I believe the charge transition levels are also referenced to the VBM. It will be useful to add this in the usage notes section.
2. Is it possible to take DFT relaxed structure file of the bulk calculation as input (along with the DOS, as already implemented) to the code instead of providing manual inputs for parameters such volume, bandgap, nelect? 

I fear user may easily mix-up these values if not entered carefully.

**Comment by bjmorgan** [comment]
1. Good suggestion.
2. The intention for the code was to be somewhat "DFT code agnostic", so that people can more easily integrate it into their own custom workflows. Processing data directly from a set of DFT inputs requires 1. specifying how these data are presented (you need a self-consistent set of DFT outputs to define a full defect system) and 2. writing custom parsers that then steer users towards specific codes or workflows.

**Comment by alexsquires** [comment]
1. agreed!
2. You can in fact read the volume from any structure file (which is compatible with pymatgen), or a structure file formatted from the original `SC-Fermi` code.  (see `py-sc-fermi.inputs`). I am happy to highlight this in the docs.

**Comment by bjmorgan** [comment]
Yes. I think we would discourage users from inputting any data anywhere manually. These should be pulled programmatically from their DFT calculations.

**Comment by ajgoyal** [comment]
Thank you both. I will close the issue.

**Comment by ajgoyal** [comment]
Thanks for promptly taking the suggestions.
